spring:
  cloud:
    stream:
      default:
        producer:
          error-channel-enabled: true

      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          min-partition-count: 3
          replication-factor: 3
          configuration:
            acks: -1
            reconnect.backoff.max.ms: 120000

        bindings:
          my-prod-input:
            consumer:
              auto-commit-offset: false
              destination-is-pattern: true

      bindings:
        my-prod-input:
          destination: test-prod.*-topic,foo
          group: test-prod-group
          consumer:
            batch-mode: true
